name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Run Python tests 
      run: |
        sudo python3 -m pip install pyyaml
        sudo python3 -m unittest tests.test_fetch -v
        sudo python3 -m unittest tests.test_save -v
